### ISSUE TITLE
qwen/Qwen-7B-Chat下载失败，是什么地方需要登录吗？

### ISSUE THREAD

**Issue by Himan000** [modelscope/motionagent#7]
生成剧本时，拿不到模型，看报错是需要登录，但是在什么地方登录呢？

2023-09-20 19:59:22,024 - modelscope - ERROR - Authentication token does not exist, failed to access model qwen/Qwen-7B-Chat which may not exist or may be                 private. Please login first.
Traceback (most recent call last):
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/modelscope/hub/errors.py", line 81, in handle_http_response
    response.raise_for_status()
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://www.modelscope.cn/api/v1/models/qwen/Qwen-7B-Chat/revisions?EndTime=1695211162

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 36, in qwen_script
    script = qwen_infer_p(inputs=inputs)
  File "/service/motionagent/inference/qwen_infer.py", line 45, in qwen_infer
    tokenizer = AutoTokenizer.from_pretrained("qwen/Qwen-7B-Chat", revision = 'v1.0.1',trust_remote_code=True)
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/modelscope/utils/hf_util.py", line 90, in from_pretrained
    model_dir = snapshot_download(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 96, in snapshot_download
    revision = _api.get_valid_revision(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/modelscope/hub/api.py", line 479, in get_valid_revision
    revisions = self.list_model_revisions(
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/modelscope/hub/api.py", line 433, in list_model_revisions
    handle_http_response(r, logger, cookies, model_id)
  File "/app/anaconda3/envs/motion_agent/lib/python3.8/site-packages/modelscope/hub/errors.py", line 88, in handle_http_response
    raise HTTPError('Response details: %s' % message) from error
requests.exceptions.HTTPError: Response details: {'Code': 10010200001, 'Message': '获取模型版本失败，信息：获取模失败', 'RequestId': 'e10a8569-e157-4607-98be-8409d70e4e1f', 'Success': False}

**Comment by yingdachen** [comment]
目前千问7B的官方模型正在升级中，计划近期会重新上线。

您也可以在modelscope站点搜索qwen，有开发者自己上传的之前的版本。

**Comment by Himan000** [comment]
您好！我在huggingface下载了相应的qwen模型，但是测试的时候发现如下错误：

**Comment by Himan000** [comment]
已解决，通过手动下载模型，更改一个Qwen->qwen的错误路径解决，谢谢
