### ISSUE TITLE
DSW部署motionagent时，报错。真的很想使用motionagent，我浏览了一下b站有很多人出现类似问题，是否可以解答一下，感激不尽！

### ISSUE THREAD

**Issue by Badtreater** [modelscope/motionagent#9]
**问题如下：**
**步骤**：motionagent# pip3 install -r requirements.txt中

**报错内容：**
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5wqbzv4h/audiocraft_a3fa9fee14b4408daf5895e606fd4ca3/setup.py", line 19, in <module>
          REQUIRED = [i.strip() for i in open("requirements.txt")]
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

十分感谢开发者能推出该项目，希望以后自己可以成为忠实粉丝，谢谢！

**Comment by Badtreater** [comment]
**报错位置**
 Using cached https://mirrors.aliyun.com/pypi/packages/19/0e/12769f3ffb71c8e341f602000e78b674acf77190daae32ba64c7fc81b8f7/audiocraft-0.0.0.tar.gz (1.5 kB)
  Preparing metadata (setup.py) ... error

**Comment by Badtreater** [comment]
**补充**
运行：motionagent# python3 app.py
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
应该是gradio库没有安装成功，是否是因为我python版本的问题？

**Comment by Badtreater** [comment]
**补充：**
报错位置上部分信息：
Collecting audiocraft (from -r requirements.txt (line 17))
  Using cached https://mirrors.aliyun.com/pypi/packages/2a/db/3c743a447bd2d5ce65db577efdaa0986c0d51524193b9d0491dfcf75e190/audiocraft-1.0.0.tar.gz (609 kB)
  Preparing metadata (setup.py) ... done
  Using cached https://mirrors.aliyun.com/pypi/packages/57/a9/444ad0d90af627237dbaad02d4f4a7be5445af47fefa558daf793a063f78/audiocraft-0.0.2.tar.gz (423 kB)
  Preparing metadata (setup.py) ... done
  Using cached https://mirrors.aliyun.com/pypi/packages/40/be/e1945cc51d2bfcf9a7dd349ddb8be29a1bca30b099e687dbc067ee90ccb3/audiocraft-0.0.1.tar.gz (259 kB)
  Preparing metadata (setup.py) ... done
  Using cached https://mirrors.aliyun.com/pypi/packages/19/0e/12769f3ffb71c8e341f602000e78b674acf77190daae32ba64c7fc81b8f7/audiocraft-0.0.0.tar.gz (1.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

**Comment by Coco-XiangLi** [comment]
我也遇到了类似的问题，先pip install autocraft成功后，继续pip3 install -r requirements.txt，但还是出现一样的错误。。。
然后索性直接运行python app.py了，会报少量的库没安装好，挨个装上之后，可以正常运行

**Comment by Badtreater** [comment]
> 我也遇到了类似的问题，先pip install autocraft成功后，继续pip3 install -r requirements.txt，但还是出现一样的错误。。。 然后索性直接运行python app.py了，会报少量的库没安装好，挨个装上之后，可以正常运行

怎么样  运行算力要求高吗？使用稳定吗？

**Comment by Badtreater** [comment]
> 我也遇到了类似的问题，先pip install autocraft成功后，继续pip3 install -r requirements.txt，但还是出现一样的错误。。。 然后索性直接运行python app.py了，会报少量的库没安装好，挨个装上之后，可以正常运行

我按照你说的解决了环境问题，最后网络连接不上，你有遇到吗？运行app之后，显示连接失败，具体如下：
Could not create share link. Missing file: /opt/conda/envs/motion_agent/lib/python3.8/site-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /opt/conda/envs/motion_agent/lib/python3.8/site-packages/gradio

**Comment by Badtreater** [comment]
> 我也遇到了类似的问题，先pip install autocraft成功后，继续pip3 install -r requirements.txt，但还是出现一样的错误。。。 然后索性直接运行python app.py了，会报少量的库没安装好，挨个装上之后，可以正常运行

我已经可以打开链接进行操作了，但是输入文本之后屏幕显示erro，后台终端显示：ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
我安装了这个tiktoken包之后还是没有解决，你有遇到这个问题吗？

**Comment by Coco-XiangLi** [comment]
> > 我也遇到了类似的问题，先pip install autocraft成功后，继续pip3 install -r requirements.txt，但还是出现一样的错误。。。 然后索性直接运行python app.py了，会报少量的库没安装好，挨个装上之后，可以正常运行
> 
> 我已经可以打开链接进行操作了，但是输入文本之后屏幕显示erro，后台终端显示：ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken` 我安装了这个tiktoken包之后还是没有解决，你有遇到这个问题吗？

不知道你现在解决了没有，我没有遇到这个tiktoken的问题。可以尝试使用pip install 或者 conda install 多安装几次。
使用还算稳定，算力使用在生成视频部分会高一些。我使用的是一张A40显卡。

**Comment by dandelion915** [comment]
我也遇到了这个问题，楼主搞好了吗
